# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/booking.BookingService/Login',
                request_serializer=booking__pb2.LoginRequest.SerializeToString,
                response_deserializer=booking__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/booking.BookingService/Logout',
                request_serializer=booking__pb2.LogoutRequest.SerializeToString,
                response_deserializer=booking__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetAvailability = channel.unary_unary(
                '/booking.BookingService/GetAvailability',
                request_serializer=booking__pb2.GetAvailabilityRequest.SerializeToString,
                response_deserializer=booking__pb2.GetAvailabilityResponse.FromString,
                _registered_method=True)
        self.BookSeat = channel.unary_unary(
                '/booking.BookingService/BookSeat',
                request_serializer=booking__pb2.BookSeatRequest.SerializeToString,
                response_deserializer=booking__pb2.BookSeatResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=booking__pb2.LoginRequest.FromString,
                    response_serializer=booking__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=booking__pb2.LogoutRequest.FromString,
                    response_serializer=booking__pb2.LogoutResponse.SerializeToString,
            ),
            'GetAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailability,
                    request_deserializer=booking__pb2.GetAvailabilityRequest.FromString,
                    response_serializer=booking__pb2.GetAvailabilityResponse.SerializeToString,
            ),
            'BookSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.BookSeat,
                    request_deserializer=booking__pb2.BookSeatRequest.FromString,
                    response_serializer=booking__pb2.BookSeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/Login',
            booking__pb2.LoginRequest.SerializeToString,
            booking__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/Logout',
            booking__pb2.LogoutRequest.SerializeToString,
            booking__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetAvailability',
            booking__pb2.GetAvailabilityRequest.SerializeToString,
            booking__pb2.GetAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/BookSeat',
            booking__pb2.BookSeatRequest.SerializeToString,
            booking__pb2.BookSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
