# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"5\n\x13GetLLMAnswerRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"&\n\x14GetLLMAnswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2Q\n\nLLMService\x12\x43\n\x0cGetLLMAnswer\x12\x18.llm.GetLLMAnswerRequest\x1a\x19.llm.GetLLMAnswerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLLMANSWERREQUEST']._serialized_start=18
  _globals['_GETLLMANSWERREQUEST']._serialized_end=71
  _globals['_GETLLMANSWERRESPONSE']._serialized_start=73
  _globals['_GETLLMANSWERRESPONSE']._serialized_end=111
  _globals['_LLMSERVICE']._serialized_start=113
  _globals['_LLMSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
